version: "3.9"
services:
    backend:
        build: ./backend
        container_name: backend
        restart: always
        volumes:
            - "./backend:/usr/src/app"
        ports:
            - 8000:8000

    frontend:
        build: ./frontend
        container_name: frontend
        restart: always
        volumes:
            - "./frontend:/app"
        ports:
            - 8080:80