version: "3.9"
services:
    logging:
        build: ./logging
        container_name: logging
        restart: always
        ports:
            - "8005:8005"

    frontend_ms:
        build: ./frontend
        container_name: frontend_ms
        restart: always
        ports:
            - 8006:80    
                  
networks:
  default:
    external: true
    name: labmustafa_default
