version: "3.9"
services:
    backend:
        image: derbuda/ms-worklist
        container_name: backend
        restart: always

    frontend:
        image: derbuda/ms-worklistf
        container_name: frontend
        restart: always

    nginx:
        image: derbuda/ms-worklistr
        container_name: nginx
        restart: always
        depends_on:
            - "frontend"
            - "backend"
        ports:
            - "80:80"