version: "3.9"
services:
    logging:
        build: ./logging
        container_name: logging
        restart: always
        ports:
            - "8005:8005"
networks:
  default:
    external: true
    name: labmustafa_default
